### ISSUE TITLE
Please bump version to 0.9.13

### ISSUE THREAD

**Issue by runningman84** [hw-cookbooks/graphite#217]
0.9.13 contains major performance improvements for grafana.

**Comment by alecxvs** [comment]
This issue may prevent some people (like me) from using 0.9.13 however:
https://github.com/graphite-project/carbon/issues/355

It may be worth noting that the source option ignores version since it pulls from master so there's no workaround to get the 0.9.13 release currently.

**Comment by iennae** [comment]
This currently looks to be resolved as the version is now default['graphite']['version'] = '0.9.15' in the default attributes file. Can you confirm?

**Comment by runningman84** [comment]
Yes
