### ISSUE TITLE
Ordering of graphite_storage_schema

### ISSUE THREAD

**Issue by erez-rabih** [hw-cookbooks/graphite#218]
I'm trying to create two storage schemas. The problem is that they are always written to the conf file in the same order, no matter how I order them in the cookbook. It always writes the "catchall" schema first so all other definitions which follow are ignored (since catch all always matches the stat pattern)

This is what I'm trying to do 
```ruby
graphite_storage_schema "stats" do
  config ({
    pattern: "^stats.",
    retentions: "5s:6h,1min:7d,10min:5y"
  })
end

graphite_storage_schema "catchall" do
  config ({
    pattern: "^.*",
    retentions: "5s:6h,1min:7d,10min:5y"
  })
end
```
And the output file is always (even when I change the order in the recipe):
```
      +# This file is managed by Chef, your changes *will* be overwritten!
      +
      +[catchall]
      +PATTERN = ^.*
      +RETENTIONS = 60:100800,900:63000
      +
      +[stats]
      +PATTERN = ^stats.
      +RETENTIONS = 5s:6h,1min:7d,10min:5y
```

How can I force order of schemas into the file?

Thanks!

**Comment by alindeman** [comment]
I ran into this too. From a little digging into the code, it appears the keys are sorted. I think this is very surprising behavior, especially in the case of `storage-schemas.conf`, where order matters.

For now, I think a solution might be:

```ruby
graphite_storage_schema "00-stats" do
  # ...
end

graphite_storage_schema "99-catchall" do
  # ...
end
```

**Comment by ianbamforth** [comment]
Bit me too, pretty important issue!  Unless a fix is imminent (given the age of this issue, I expect not), can I suggest a big old warning in the readme file in the interim?  Something in a massive font, using bold and capital letters should be about right.
