### ISSUE TITLE
Supermarket Release ahead of Git Release

### ISSUE THREAD

**Issue by gwaldo** [hw-cookbooks/graphite#237]
supermarket.chef.io is showing cookbook release at v1.0.2, but this git repo shows latest as v1.0.1

**Comment by iennae** [comment]
Hey @gwaldo,

Apologies for the delay in response to your inquiry here. In general not all of the cookbook repos use the git release functionality. It's more useful to look at the changes and look for the metadata update there, i.e. https://github.com/hw-cookbooks/graphite/commits/develop. I did notice that the metadata is currently showing 1.0.5 so I imagine that there is an impending release to 1.0.5.
