### ISSUE TITLE
Not pinning dependent cookbooks causes issues for chef 11.x users

### ISSUE THREAD

**Issue by drenalin23** [hw-cookbooks/graphite#239]
This cookbook depends on memcached.  When memcached upgraded to version 2.0.0, they included the compat_resource cookbook as a dependency - which breaks a chef 11.x convergence since compat_resource if only compatible with Chef 12.x.
You should consider pinning or soft-pinning the dependencies in this cookbook so they don't end up breaking later by upgrades of the dependent cookbooks.

**Comment by tas50** [comment]
Looks like the memcached cookbook isn't actually used by this cookbook, so that can get removed.

**Comment by tas50** [comment]
Fixed in https://github.com/hw-cookbooks/graphite/commit/1f649138a4a222a2a81ff47be9555a1b3cb4111b
