### ISSUE TITLE
Dangerous reordering of Carbon .ini sections

### ISSUE THREAD

**Issue by satiani** [hw-cookbooks/graphite#241]
Right now in `cookbooks/graphite/libraries/chef_graphite.rb` the INI file sections are generated as such:

```ruby
     def generate_conf_data(data)
      tuples = sort_tuples(section_tuples(data))

       result = Hash.new
       tuples.each { |tuple| result[tuple.first] = tuple.last }
       result
     end

    def sort_tuples(tuples)
      tuples.sort { |a, b| a.first <=> b.first }
    end
```

Which means that sections are reordered by section name alphabetically rather than by the order they are defined in the file. This is dangerous since carbon is order-sensitive when it parses the rules in INI files. For example, in `single_node.rb` example in the cookbook, you have the following:

```ruby
graphite_storage_schema "carbon" do
  config ({
            pattern: "^carbon\.",
            retentions: "60:90d"
          })
end

graphite_storage_schema "default_1min_for_1day" do
  config ({
            pattern: ".*",
            retentions: "60s:1d"
          })
end
```

In this case, the insertion order is the same as the alphabetic order ("carbon" then "default_1min_for_1day"). If you switch the names around the pattern `.*` will catch everything and the "carbon" rule will never be matched, resulting in completely different behavior and expensively unexpected results.

**Comment by satiani** [comment]
The solution for ruby 1.9+ is simple: remove `sort_tuples` function. For earlier versions, you'll have to use some ordered hash implementation throughout or to keep the order in an independent list.

**Comment by cwjohnston** [comment]
Duplicates #218
