### ISSUE TITLE
Route around latest minor release breaking changes?

### ISSUE THREAD

**Issue by luckymike** [hw-cookbooks/graphite#249]
Chef 12.7 & 12.8 seem to have a behavior change which causes a converge failure on `pip install uwsgi`

See: https://github.com/chef/chef/issues/4702

So far we've only observed this on Ubuntu 12.04, as the uwsgi warnings seem to be specific to 12.04's Python version.

We could potentially isolate a workaround to Ubuntu 12.04 & Chef Client > 12.6 where we ignore errors on `pip install uwsgi`, though it'd be preferable for Chef to release a patched version.

Thoughts?

**Comment by luckymike** [comment]
Following education about reasons, I now know this is not a regression in chef. We'll need to replace python_pip with python_package to get the fix, which will drop Chef 11 support, I believe. So yeah, we'll need to sort that out. 

In the meantime, this does not work with Ubuntu 12.04 and chef > 12.6

**Comment by webframp** [comment]
In the short term should we at least add a note to the readme.md on master?

**Comment by luckymike** [comment]
Yeah, will create an issue!
