### ISSUE TITLE
Travis CI not building PRs

### ISSUE THREAD

**Issue by webframp** [hw-cookbooks/graphite#255]
The repo has a .travis.yml, we're currently up to PR #246 but the last PR build shown in Travis is #213 

https://travis-ci.org/hw-cookbooks/graphite/pull_requests

What's missing?

I don't currently have rights to adjust settings for the repo, so just opening an issue.

**Comment by tas50** [comment]
The config in travis all looks good.  I'm a bit baffled by this one
